name: CI To-Do List

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-quality:
    runs-on: ubuntu-latest
    
    # Esta parte força o uso do Node.js 24 para evitar avisos de obsolescência
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Baixando o código do repositório
        uses: actions/checkout@v4

      - name: Configurando ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Executando Testes Unitários
        run: node testes.js
